#
#
#

language: bash
sudo: true

branches:
  only:
    - master

git:
  submodules: false

env:
  global:
    - PANDOC_DIR=${TRAVIS_BUILD_DIR}/deps/pandoc
    - PANDOC_BIN_DIR=${PANDOC_DIR}/bin
    - PANDOC_ARCHIVE=pandoc-1.19.2.1-1-amd64.deb
    - PANDOC_URL=https://github.com/jgm/pandoc/releases/download/1.19.2.1/${PANDOC_ARCHIVE}

before_install:
  - mkdir -p ${PANDOC_DIR}
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - travis_retry wget ${PANDOC_URL}
  - ar p ${PANDOC_ARCHIVE} data.tar.gz | tar xvz --strip-components 2 -C ${PANDOC_DIR}
  - export PATH=${PATH}:${PANDOC_BIN_DIR}
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
  - sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
  - sudo apt-get install texlive-bibtex-extra texlive-science lmodern dvipng 

before_script:
  - mkdir -p build && cd build

script:
  - cmake ..
  - source exports.sh && make

notifications:
  slack:
    on_success: change
    on_failure: change

