#
#
#

language: bash
sudo: true

branches:
  only:
    - master

env:
  global:
    - PANDOC_DIR=${TRAVIS_BUILD_DIR}/deps/pandoc
    - PANDOC_BIN_DIR=${PANDOC_DIR}/usr/bin
    - PANDOC_ARCHIVE=https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb

before_install:
  - wget ${PANDOC_ARCHIVE} | ar p | tar zx -C ${PANDOC_DIR}
  - export PATH=${PATH}:${PANDOC_BIN_DIR}
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update -qq
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
  - sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
  - sudo apt-get install texlive-science
  - sudo apt-get install lmodern

before_script:
  - source utils/scripts/exports.sh
  - mkdir -p build && cd build

script:
  - cmake ..
  - cmake --build . -- -j$(nproc)
  - cmake --build . --target unittests -- -j$(nproc)
  - if [[ $PRJ_SKIP_TESTS == "OFF" ]]; then ./run_unit_tests.sh; fi
  - cmake --build . --target install

notifications:
  slack:
    on_success: change
    on_failure: change

